name: run-kubectl
author: Myrotvorets
description: kubectl as a GitHub Action
inputs:
  config:
    required: true
    description: BASE64-encoded kubeconfig
  version:
    default: latest
    required: false
    description: kubectl version (1.18, 1.19, 1.20, 1.21, 1.22, 1.23, 1.24, latest)
runs:
  using: docker
  image: docker://myrotvorets/kubectl-action:latest
  env:
    KUBECTL_VERSION: ${{ inputs.version }}
    KUBE_CONFIG_DATA: ${{ inputs.config }}
branding:
  icon: terminal
  color: blue
